version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: pollos-chanchos-angular-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_avicola
      MYSQL_USER: avicola_user
      MYSQL_PASSWORD: avicola_password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  backend:
    build: ./backend
    container_name: pollos-chanchos-angular-backend
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_PORT=8088
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/db_avicola?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=avicola_user
      - SPRING_DATASOURCE_PASSWORD=avicola_password
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    # (Healthcheck removido para evitar depender de /actuator/health o /health)
    volumes:
      - uploads_data:/app/uploads

  frontend:
    build: ./frontend
    container_name: pollos-chanchos-angular-frontend
    ports:
      - "8004:80"
      # - "443:443"    # Comenta o elimina esta línea si Nginx maneja el SSL en el host
    depends_on:
      backend:
        condition: service_started
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

volumes:
  mysql_data:
  uploads_data:

networks:
  app-network:
    driver: bridge