version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: pollos-chanchos-angular-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_avicola
      MYSQL_USER: avicola_user
      MYSQL_PASSWORD: avicola_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: pollos-chanchos-angular-backend
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_PORT=8088
      - DB_HOST=mysql
  - DB_PORT=3307
      - DB_NAME=db_avicola
      - DB_USER=avicola_user
      - DB_PASSWORD=avicola_password
    depends_on:
      - mysql
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: pollos-chanchos-angular-frontend
    ports:
      - "8004:80"      # <-- Solo cambia esta línea
      # - "443:443"    # Comenta o elimina esta línea si Nginx maneja el SSL en el host
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge