version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_avicola
      MYSQL_USER: avicola_user
      MYSQL_PASSWORD: avicola_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_PORT=8088
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=db_avicola
      - DB_USER=avicola_user
      - DB_PASSWORD=avicola_password
    depends_on:
      - mysql
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge