services:
  postgres:
    image: postgres:16
    container_name: pollos-chanchos-angular-postgres
    environment:
      POSTGRES_DB: db_avicola
      POSTGRES_USER: avicola_user
      POSTGRES_PASSWORD: avicola_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U avicola_user -d db_avicola"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  backend:
    build: ./backend
    container_name: pollos-chanchos-angular-backend
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_PORT=8088
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=db_avicola
      - DB_USER=avicola_user
      - DB_PASSWORD=avicola_password
      - APP_UPLOAD_DIR=/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - uploads_data:/app/uploads

  frontend:
    build: ./frontend
    container_name: pollos-chanchos-angular-frontend
    ports:
      - "18080:80"
      - "18088:80"
      - "8004:80"
    depends_on:
      backend:
        condition: service_started
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  postgres_data:
  uploads_data:

networks:
  app-network:
    driver: bridge
