version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8088:8088"  # Puerto correcto del backend Spring Boot
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_PORT=8088
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge