services:
  mysql:
    image: mysql:8.0
    container_name: pollos-chanchos-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Alexandra1
      MYSQL_DATABASE: db_avicola
      MYSQL_USER: root
      MYSQL_PASSWORD: Alexandra1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: pollos-chanchos-backend
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_PORT=8088
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/db_avicola
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Alexandra1
    depends_on:
      - mysql
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pollos-chanchos-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge