name: Backend CI/CD

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache de dependencias de Maven
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Construir y probar con Maven
      run: mvn -B package --file pom.xml

    - name: Subir artefacto de build
      uses: actions/upload-artifact@v3
      with:
        name: spring-boot-app
        path: backend/target/*.jar