name: Frontend CI/CD

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'frontend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Cache de dependencias de Node
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Instalar dependencias
      run: npm install

    - name: Construir proyecto
      run: npm run build -- --configuration production

    - name: Ejecutar pruebas
      run: npm test -- --watch=false --browsers=ChromeHeadless

    - name: Subir artefacto de build
      uses: actions/upload-artifact@v3
      with:
        name: angular-app
        path: frontend/dist/